=== Almaroo/InteractivePeriodicTable/xml/uop_ready.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="localhost" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="note" type="loc:noteType" xmlns:loc="localhost"/>
  <xs:complexType name="elementType">
    <xs:sequence>
      <xs:element type="xs:positiveInteger" name="number"/>
      <xs:element name="symbol">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="3"/>
            <xs:pattern value="[A-Z][a-z]*"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="2"/>
            <xs:pattern value="[A-Z][a-z]*"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:float" name="mass"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="family"/>
  </xs:complexType>
  <xs:complexType name="elementsType">
    <xs:sequence>
      <xs:element type="loc:elementType" name="element" maxOccurs="unbounded" minOccurs="0" xmlns:loc="localhost"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="noteType">
    <xs:sequence>
      <xs:element type="loc:elementsType" name="elements" xmlns:loc="localhost"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Almaroo/InteractivePeriodicTable/xml/uop_ready.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Odkomentowane pozwalało sprawdzać wprowadzanie nowych pierwiastków w WebStorms IDE
<note xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="localhost"
      xsi:schemaLocation="localhost uop_ready.xsd">
	  -->
    <elements>
        <element family="nonmetal">
            <number>1</number>
            <symbol>H</symbol>
            <name>Hydrogen</name>
            <mass>1.00794</mass>
        </element>
        <element family="noble gas">
            <number>2</number>
            <symbol>He</symbol>
            <name>Helium</name>
            <mass>4.002602</mass>
        </element>
        <element family="alkali metal">
            <number>3</number>
            <symbol>Li</symbol>
            <name>Lithium</name>
            <mass>6.941</mass>
        </element>
        <element family="alkaline earth metal">
            <number>4</number>
            <symbol>Be</symbol>
            <name>Beryllium</name>
            <mass>9.012182</mass>
        </element>
        <element family="metalloid">
            <number>5</number>
            <symbol>B</symbol>
            <name>Boron</name>
            <mass>10.811</mass>
        </element>
        <element family="nonmetal">
            <number>6</number>
            <symbol>C</symbol>
            <name>Carbon</name>
            <mass>12.0107</mass>
        </element>
        <element family="nonmetal">
            <number>7</number>
            <symbol>N</symbol>
            <name>Nitrogen</name>
            <mass>14.0067</mass>
        </element>
        <element family="nonmetal">
            <number>8</number>
            <symbol>O</symbol>
            <name>Oxygen</name>
            <mass>15.9994</mass>
        </element>
        <element family="halogen">
            <number>9</number>
            <symbol>F</symbol>
            <name>Fluorine</name>
            <mass>18.9984032</mass>
        </element>
        <element family="noble gas">
            <number>10</number>
            <symbol>Ne</symbol>
            <name>Neon</name>
            <mass>20.1797</mass>
        </element>
        <element family="alkali metal">
            <number>11</number>
            <symbol>Na</symbol>
            <name>Sodium</name>
            <mass>22.98976928</mass>
        </element>
        <element family="alkaline earth metal">
            <number>12</number>
            <symbol>Mg</symbol>
            <name>Magnesium</name>
            <mass>24.305</mass>
        </element>
        <element family="metal">
            <number>13</number>
            <symbol>Al</symbol>
            <name>Aluminum</name>
            <mass>26.9815386</mass>
        </element>
        <element family="metalloid">
            <number>14</number>
            <symbol>Si</symbol>
            <name>Silicon</name>
            <mass>28.0855</mass>
        </element>
        <element family="nonmetal">
            <number>15</number>
            <symbol>P</symbol>
            <name>Phosphorus</name>
            <mass>30.973762</mass>
        </element>
        <element family="nonmetal">
            <number>16</number>
            <symbol>S</symbol>
            <name>Sulfur</name>
            <mass>32.065</mass>
        </element>
        <element family="halogen">
            <number>17</number>
            <symbol>Cl</symbol>
            <name>Chlorine</name>
            <mass>35.453</mass>
        </element>
        <element family="noble gas">
            <number>18</number>
            <symbol>Ar</symbol>
            <name>Argon</name>
            <mass>39.948</mass>
        </element>
        <element family="alkali metal">
            <number>19</number>
            <symbol>K</symbol>
            <name>Potassium</name>
            <mass>39.0983</mass>
        </element>
        <element family="alkaline earth metal">
            <number>20</number>
            <symbol>Ca</symbol>
            <name>Calcium</name>
            <mass>40.078</mass>
        </element>
        <element family="transition metal">
            <number>21</number>
            <symbol>Sc</symbol>
            <name>Scandium</name>
            <mass>44.955912</mass>
        </element>
        <element family="transition metal">
            <number>22</number>
            <symbol>Ti</symbol>
            <name>Titanium</name>
            <mass>47.867</mass>
        </element>
        <element family="transition metal">
            <number>23</number>
            <symbol>V</symbol>
            <name>Vanadium</name>
            <mass>50.9415</mass>
        </element>
        <element family="transition metal">
            <number>24</number>
            <symbol>Cr</symbol>
            <name>Chromium</name>
            <mass>51.9961</mass>
        </element>
        <element family="transition metal">
            <number>25</number>
            <symbol>Mn</symbol>
            <name>Manganese</name>
            <mass>54.938045</mass>
        </element>
        <element family="transition metal">
            <number>26</number>
            <symbol>Fe</symbol>
            <name>Iron</name>
            <mass>55.845</mass>
        </element>
        <element family="transition metal">
            <number>27</number>
            <symbol>Co</symbol>
            <name>Cobalt</name>
            <mass>58.933195</mass>
        </element>
        <element family="transition metal">
            <number>28</number>
            <symbol>Ni</symbol>
            <name>Nickel</name>
            <mass>58.6934</mass>
        </element>
        <element family="transition metal">
            <number>29</number>
            <symbol>Cu</symbol>
            <name>Copper</name>
            <mass>63.546</mass>
        </element>
        <element family="transition metal">
            <number>30</number>
            <symbol>Zn</symbol>
            <name>Zinc</name>
            <mass>65.38</mass>
        </element>
        <element family="metal">
            <number>31</number>
            <symbol>Ga</symbol>
            <name>Gallium</name>
            <mass>69.723</mass>
        </element>
        <element family="metalloid">
            <number>32</number>
            <symbol>Ge</symbol>
            <name>Germanium</name>
            <mass>72.64</mass>
        </element>
        <element family="metalloid">
            <number>33</number>
            <symbol>As</symbol>
            <name>Arsenic</name>
            <mass>74.9216</mass>
        </element>
        <element family="nonmetal">
            <number>34</number>
            <symbol>Se</symbol>
            <name>Selenium</name>
            <mass>78.96</mass>
        </element>
        <element family="halogen">
            <number>35</number>
            <symbol>Br</symbol>
            <name>Bromine</name>
            <mass>79.904</mass>
        </element>
        <element family="noble gas">
            <number>36</number>
            <symbol>Kr</symbol>
            <name>Krypton</name>
            <mass>83.798</mass>
        </element>
        <element family="alkali metal">
            <number>37</number>
            <symbol>Rb</symbol>
            <name>Rubidium</name>
            <mass>85.4678</mass>
        </element>
        <element family="alkaline earth metal">
            <number>38</number>
            <symbol>Sr</symbol>
            <name>Strontium</name>
            <mass>87.62</mass>
        </element>
        <element family="transition metal">
            <number>39</number>
            <symbol>Y</symbol>
            <name>Yttrium</name>
            <mass>88.90585</mass>
        </element>
        <element family="transition metal">
            <number>40</number>
            <symbol>Zr</symbol>
            <name>Zirconium</name>
            <mass>91.224</mass>
        </element>
        <element family="transition metal">
            <number>41</number>
            <symbol>Nb</symbol>
            <name>Niobium</name>
            <mass>92.90638</mass>
        </element>
        <element family="transition metal">
            <number>42</number>
            <symbol>Mo</symbol>
            <name>Molybdenum</name>
            <mass>95.96</mass>
        </element>
        <element family="transition metal">
            <number>43</number>
            <symbol>Tc</symbol>
            <name>Technetium</name>
            <mass>98</mass>
        </element>
        <element family="transition metal">
            <number>44</number>
            <symbol>Ru</symbol>
            <name>Ruthenium</name>
            <mass>101.07</mass>
        </element>
        <element family="transition metal">
            <number>45</number>
            <symbol>Rh</symbol>
            <name>Rhodium</name>
            <mass>102.9055</mass>
        </element>
        <element family="transition metal">
            <number>46</number>
            <symbol>Pd</symbol>
            <name>Palladium</name>
            <mass>106.42</mass>
        </element>
        <element family="transition metal">
            <number>47</number>
            <symbol>Ag</symbol>
            <name>Silver</name>
            <mass>107.8682</mass>
        </element>
        <element family="transition metal">
            <number>48</number>
            <symbol>Cd</symbol>
            <name>Cadmium</name>
            <mass>112.411</mass>
        </element>
        <element family="metal">
            <number>49</number>
            <symbol>In</symbol>
            <name>Indium</name>
            <mass>114.818</mass>
        </element>
        <element family="metal">
            <number>50</number>
            <symbol>Sn</symbol>
            <name>Tin</name>
            <mass>118.71</mass>
        </element>
        <element family="metalloid">
            <number>51</number>
            <symbol>Sb</symbol>
            <name>Antimony</name>
            <mass>121.76</mass>
        </element>
        <element family="metalloid">
            <number>52</number>
